#cloud-config

package_update: true
package_upgrade: true

packages:
  - net-tools

runcmd:
  - |
    ##Create devops user
    sudo useradd -m -s /bin/bash devops
    sudo usermod -aG sudo devops
    echo "devops:devops" | sudo chpasswd

    ##setting up kubectl
    sudo snap install kubectl --classic
    #bash-completion
    sudo apt-get install bash-completion
    source /usr/share/bash-completion/bash_completion
    echo 'source <(kubectl completion bash)' >> /home/devops/.bashrc
    #alias for kubectl
    echo 'alias k=kubectl' >> /home/devops/.bashrc
    echo 'complete -o default -F __start_kubectl k' >> /home/devops/.bashrc

    # # Configure SSH
    # sudo sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
    # sudo systemctl restart sshd

    # Install Docker
    sudo apt-get update -y
    sudo apt-get install ca-certificates curl gnupg -y
    sudo install -m 0755 -d /etc/apt/keyrings
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
    sudo chmod a+r /etc/apt/keyrings/docker.gpg
    echo \
      "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
      $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
      sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
    sudo apt-get update -y
    sudo apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose -y
    sudo usermod -aG docker devops
    sudo systemctl enable --now docker

    ##setup kind cluster
    curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.21.0/kind-linux-amd64
    chmod +x ./kind
    sudo mv ./kind /usr/local/bin/kind
    kind create cluster --name my-cluster --config <(echo "kind: Cluster
    apiVersion: kind.x-k8s.io/v1alpha4
    nodes:
    - role: control-plane
    - role: worker
    - role: worker")
    kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.13.7/config/manifests/metallb-native.yaml

    ##install istioctl
    curl -L https://istio.io/downloadIstio | ISTIO_VERSION=1.20.3 TARGET_ARCH=x86_64 sh -
    export PATH="$PATH:/home/devops/istio-1.20.3/bin"
    istioctl install --set profile=default -y