#cloud-config

package_update: true
package_upgrade: true

packages:
  - net-tools
  - openjdk-17-jre-headless

runcmd:
  - |
    ##Create devops user
    sudo useradd -m -s /bin/bash devops
    sudo usermod -aG sudo devops
    echo "devops:devops" | sudo chpasswd
    sudo hostnamectl set-hostname jenkins-master

    # # Configure SSH
    # sudo sed -i 's/#PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
    # sudo systemctl restart sshd
    sudo wget -O /usr/share/keyrings/jenkins-keyring.asc \
      https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key

    echo deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] \
      https://pkg.jenkins.io/debian-stable binary/ | sudo tee \
      /etc/apt/sources.list.d/jenkins.list > /dev/null

    sudo apt-get update -y
    sudo apt-get install jenkins -y